services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_DB=onlineshop_db'
      - 'POSTGRES_PASSWORD=12345678'
    volumes:
      - '/Users/nazarii/volumes/postgres:/var/lib/postgresql/data'
