services:
  database:
    image: 'postgres:17'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=onlineshop_db'
      - 'POSTGRES_PASSWORD=12345678'
    volumes:
      - '~/volumes/nazarii/postgres:/var/lib/postgresql/data'